import time
#AREA CALCULATION of RECTANGLE 
print("HI")
time.sleep(1)
print("Pls type the following numbers properply for perimeter")
side = float(input("type length value after equal to sign = "))
side2 = float(input("type breath value after equal to sign = "))
print("calculating pls wait .......")
time.sleep(1)
print("...............................")
time.sleep(1)
print(side * 2 + side2 * 2)
print("          ")
time.sleep(1)
print("calculating area pls wait .......")
time.sleep(1)
print("................................")
time.sleep(1)
print(side * side2)
time.sleep(10)
exit()