import time
#AREA CALCULATION of TRIANGLE 
print("HI")
time.sleep(1)
print("Pls type the following numbers properply for perimeter")
height = float(input("type height value after equal to sign = "))
base = float(input("type base value after equal to sign = "))
hypotenuse = float(input("type hypotenuse value after equal to sign = "))
print("calculating pls wait .......")
time.sleep(1)
print("...............................")
time.sleep(1)
print(height + base + hypotenuse)
print("          ")
time.sleep(1)
print("calculating area pls wait .......")
time.sleep(1)
print("................................")
time.sleep(1)
print(height * base / 2)
time.sleep(10)
exit()